export const RECEIVE_WEB3_ACCOUNTS = 'RECEIVE_WEB3_ACCOUNTS'
export const ETHER_TRANSFERED = 'ETHER_TRANSFERED'
export const WEB3_SETTINGS_UPDATED = 'WEB3_SETTINGS_UPDATED'


export const Constants = {
  RECEIVE_WEB3_ACCOUNTS,
  ETHER_TRANSFERED,
  WEB3_SETTINGS_UPDATED
}
