export const MERCURY_EVENT_STORE_USER_ENCOUNTER = 'MERCURY_EVENT_STORE_USER_ENCOUNTER'
export const MERCURY_EVENT_STORE_USER_ENCOUNTER_LINKED = "MERCURY_EVENT_STORE_USER_ENCOUNTER_LINKED"

export const Constants = {
  MERCURY_EVENT_STORE_USER_ENCOUNTER,
  MERCURY_EVENT_STORE_USER_ENCOUNTER_LINKED
}
