export default [
  { value: '👑   Transmute Framework   👑' },
  { value: '🦄   $' },
  { value: '🍄  Running Truffle Migrate ...' },
  { value: 'Using network \'development\'.' },
  { value: 'Running migration: 1_initial_migration.js' },
  { value: '  Deploying Migrations...' },
  { value: '  Migrations: 0xe2e741adf12dee379140aa332edac2739a8a0793' },
  { value: 'Saving successful migration to network...' },
  { value: 'Saving artifacts...' },
  { value: 'Running migration: 2_deploy_contracts.js' },
  { value: '  Linking StringUtils to EventStoreFactory' },
  { value: '  Linking AddressSetLib to EventStoreFactory' },
  { value: '  Deploying EventStoreFactory...' },
  { value: '  EventStoreFactory: 0xff9d2e932e9ae0e4c87835c7910213bb7c608809' },
  { value: '  Linking StringUtils to MercuryEventStore' },
  { value: '  Linking AddressSetLib to MercuryEventStore' },
  { value: '  Deploying MercuryEventStore...' },
  { value: '  MercuryEventStore: 0x50dfaae84a0c735d59581039f2cfab790971387b' },
  { value: '  Linking StringUtils to MercuryEventStoreFactory' },
  { value: '  Linking AddressSetLib to MercuryEventStoreFactory' },
  { value: '  Deploying MercuryEventStoreFactory...' },
  { value: '  MercuryEventStoreFactory: 0xa47c5c0db9716b3a64723856a8c2629a29566a1c' },
  { value: 'Saving successful migration to network...' },
  { value: 'Saving artifacts...' },
  { value: '🦄   $' },
]