export const MERCURY_EVENT_STORE_ADDRESSES_RECEIVED = 'MERCURY_EVENT_STORE_ADDRESSES_RECEIVED'
export const MERCURY_EVENT_STORE_CREATED = 'MERCURY_EVENT_STORE_CREATED'

export const MERCURY_EVENT_STORE_ADDRESS_RECEIVED = 'MERCURY_EVENT_STORE_ADDRESS_RECEIVED'
export const MERCURY_EVENT_STORE_READ_MODEL_RECEIVED = 'MERCURY_EVENT_STORE_READ_MODEL_RECEIVED'

export const Constants = {
  MERCURY_EVENT_STORE_ADDRESS_RECEIVED,
  MERCURY_EVENT_STORE_ADDRESSES_RECEIVED,
  MERCURY_EVENT_STORE_CREATED,
  MERCURY_EVENT_STORE_READ_MODEL_RECEIVED
}
