export const MERCURY_EVENT_STORE_ADDRESSES_RECEIVED = 'MERCURY_EVENT_STORE_ADDRESSES_RECEIVED'
export const MERCURY_EVENT_STORE_USER_CREATED = 'MERCURY_EVENT_STORE_USER_CREATED'
export const WEB3_SETTINGS_UPDATED = 'WEB3_SETTINGS_UPDATED'


export const Constants = {
  MERCURY_EVENT_STORE_ADDRESSES_RECEIVED,
  MERCURY_EVENT_STORE_USER_CREATED,
  WEB3_SETTINGS_UPDATED
}
